<a href="https://colab.research.google.com/github/jainstuti/Tweets_classification/blob/main/ensemble_TMLC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [115]:
#importing libraries
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

In [116]:
#importing dataset
dataset = pd.read_csv('Twitter_Data.csv')

In [117]:
dataset=dataset.head(30000)

In [118]:
dataset.shape

(30000, 2)

In [119]:
# to get the values in categorical data and their counts in the data
dataset['category'].value_counts()

 1.0    12718
 0.0    10232
-1.0     7050
Name: category, dtype: int64

In [120]:
dataset.describe()

category
count  30000.000000
mean       0.188933
std        0.789467
min       -1.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        1.000000

In [121]:
dataset.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   clean_text  29999 non-null  object 
 1   category    30000 non-null  float64
dtypes: float64(1), object(1)
memory usage: 468.9+ KB


In [122]:
dataset.isnull().sum()


clean_text    1
category      0
dtype: int64

In [123]:
is_NaN = dataset.isnull()
row_has_NaN = is_NaN.any(axis=1)
rows_with_NaN = dataset[row_has_NaN]

print(rows_with_NaN)

    clean_text  category
148        NaN       0.0


In [124]:
dataset=dataset.dropna()

In [125]:
dataset = dataset.reset_index()

In [126]:
dataset.shape

(29999, 3)

In [127]:
dataset.head()

index                                         clean_text  category
0      0  when modi promised “minimum government maximum...      -1.0
1      1  talk all the nonsense and continue all the dra...       0.0
2      2  what did just say vote for modi  welcome bjp t...       1.0
3      3  asking his supporters prefix chowkidar their n...       1.0
4      4  answer who among these the most powerful world...       1.0

In [128]:
dataset =dataset.drop(['index'], axis = 1)

In [129]:
#cleaning the text
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, len(dataset)):
  tweet = re.sub("[^a-zA-Z]", " ", dataset['clean_text'][i])
  tweet = tweet.lower()
  tweet = tweet.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  tweet = [ps.stem(word) for word in tweet if not word in set(all_stopwords)]
  tweet = ' '.join(tweet)
  corpus.append(tweet)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [130]:
#creating bag of words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 3000)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, 1].values

In [131]:
X.shape

(29999, 3000)

In [132]:
#slpiiting data into training and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [140]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

clf1 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
clf2 = RandomForestClassifier(n_estimators=10, random_state=0)
clf3 = GaussianNB()

voting_clf = VotingClassifier(estimators=[('dt', clf),('rf',clf2), ('nb', clf3)])

for clf in (clf1, clf2, clf3, voting_clf):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

DecisionTreeClassifier 0.76
RandomForestClassifier 0.7751666666666667
GaussianNB 0.5876666666666667
VotingClassifier 0.7871666666666667


In [141]:

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1011  157  216]
 [ 136 1791   92]
 [ 389  287 1921]]


In [142]:
recall = np.diag(cm) / np.sum(cm, axis = 1)
precision = np.diag(cm) / np.sum(cm, axis = 0)
print(np.mean(recall))
print(np.mean(precision))

0.7857545970823346
0.773788950491061


In [143]:
f1Score = 2 * precision * recall / (precision + recall)
print(np.mean(f1Score))

0.7768670724526571
